### ISSUE TITLE
[1pt] Set up kanban board

### ISSUE THREAD

**Issue by Kwentsir** [Kwentsir/Food-Recipe-App#2]

**Comment by Kwentsir** [comment]
This is a link to the kanban board setup of our Food-Recipe project.
https://github.com/users/Kwentsir/projects/4/views/1
We are two people working on this project. 
@kamzzy 
@Kwentsir

**Comment by danmainah** [comment]
Hi @Kwentsir and @kamzzy , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Good design

# Required Changes ♻️
Kindly ensure all your cards have a task description:
![image](https://user-images.githubusercontent.com/61408860/189621425-b307daac-316b-4e85-a2ad-c64c81ce0708.png)

- [ ] Kindy ensure all tasks in the project have been assigned, and are distributed fairly among members.
- [ ] Kindly add a task to check that no N + 1 queries are happening.
![image](https://user-images.githubusercontent.com/61408860/189622486-5bee8f82-6418-4902-8a78-6691c1e2634a.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by brytebee** [comment]
Hi Team👋,

##

### Highlights💡
- Added N + 1 problem card as suggested by the previous reviewer.✔️ 
- Assigned all cards.✔️

##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/3o6fIUZTTDl0IDjbZS/giphy.gif)

Good luck! 🎉 

##

###  **Optional Suggestions:**
- N/A

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
